---
title: "Rstanarm delta model example"
output: html_notebook
---
Example standardization of CalCOFI larval samples provided by Charlie Hinchliffe 5/12/2023
Packages

```{r}
library(tidyverse)
library(rstanarm)
```

Read data and create block factor

```{r}
mydata <- read.csv("C:/Users/r.wildermuth/Documents/FutureSeas/RecruitmentIndex/DFA_data/CalCOFI_eggs_and_larvae.csv")

mydata <- mydata %>% 
  mutate(std.egg.count = (raw.egg.count/percent.sorted)*standard.haul.factor)  %>% 
  subset(season == "winter" | season == "spring")

simple.df <- mydata %>% 
  select(std.egg.count, year, station) %>% 
  mutate(std.egg.count = round(std.egg.count, digits = 2)) %>% 
  rename(cpue = std.egg.count) %>% 
  subset(!is.na(cpue) & is.finite(cpue))

summary(is.finite(simple.df$cpue))

#Generate distance blocks station numbers
simple.df$dist_block <- NA_character_ 
simple.df$dist_block[simple.df$station < 55] <- "Block1"
simple.df$dist_block[simple.df$station >= 55 & simple.df$station < 70] <- "Block2"
simple.df$dist_block[simple.df$station >= 70 & simple.df$station < 90] <- "Block3"
simple.df$dist_block[simple.df$station >= 90] <- "Block4"
```

deltaGLMM

```{r}
# add column with response as binary
simple.df$bin <- as.numeric(simple.df$cpue>0)

# get vector of years for plots (later)
yr.vec <- unique(simple.df$year)

# convert year to factor
simple.df$year <- as.factor(simple.df$year)

simple.df$station <- as.factor(simple.df$station)

summary(simple.df)

# sample sizes by year/line
with(simple.df, table(year,dist_block))

########## fit a binomial GLM using rstanarm
# using default priors for example only... better to think more about this
binfit <- stan_glm(bin ~ year + dist_block,
                   family = binomial,
                   data = simple.df,
                   iter=2000,
                   cores = parallel::detectCores()-2)
# !! doesn't converge
summary(binfit, digits=4)

prior_summary(binfit)
# diagnostics using shiny interface:
# some parameters have effective sample sizes that are <10% of total sample size
# uncomment next line to launch diagnostic plots, etc. in web browser
# launch_shinystan(binfit)

# compare stan point estimates to glm()
binfit.mle <- glm(bin ~ year + dist_block,
                  family=binomial,
                  data=simple.df)
summary(binfit.mle)
# default priors aren't that informative in this example
plot(coef(binfit), coef(binfit.mle), xlab="posterior medians from STAN", ylab="MLEs from glm()"); abline(0,1)

# get dataframe of posterior draws
# NOTE THAT R USES 'TREATMENT' CONTRASTS BY DEFAULT,
# SO YEAR EFFECTS ARE OFFSETS FROM THE REFERENCE LEVEL
bin.draws <- as.data.frame(binfit)
summary(bin.draws); dim(bin.draws)

# get logit scale prob's for year effects
# these are for the baseline 'line' level, but it's a relative index, so not an issue
bin.yrs.logit <- cbind.data.frame(year1951=bin.draws[,1],
                                  bin.draws[,1] + bin.draws[,2:length(yr.vec)])
summary(bin.yrs.logit)
# convert to proportions
bin.yrs.prop <- exp(bin.yrs.logit) / (1 + exp(bin.yrs.logit))
summary(bin.yrs.prop)
# plot annual proportion positive
plot(yr.vec, apply(bin.yrs.prop, 2, mean), type='o', xlab='year', ylab='proportion positive')

########## fit the model for the conditional mean (given positive)
# I'm using a gamma, but you can do whatever
gamfit <- stan_glm(cpue ~ year + dist_block,
                   family = Gamma(link='log'), # gaussian(),
                   data = subset(simple.df, cpue>0),
                   iter = 2000,
                   cores = parallel::detectCores()-2)

summary(gamfit, digits=4)

prior_summary(gamfit)
# uncomment next line to launch diagnostic plots, etc. in web browser
# launch_shinystan(gamfit)

# compare stan point estimates to glm()
gamfit.mle <- glm(cpue ~ year + dist_block,
                  family = Gamma(link='log'),
                  data = subset(simple.df, cpue>0))

summary(gamfit.mle)

# default priors aren't that informative in this example
plot(coef(gamfit), coef(gamfit.mle), xlab="posterior medians from STAN", ylab="MLEs from glm()"); abline(0,1)

# get dataframe of posterior draws
# NOTE THAT R USES 'TREATMENT' CONTRASTS BY DEFAULT,
# SO YEAR EFFECTS ARE OFFSETS FROM THE REFERENCE LEVEL
gamma.draws <- as.data.frame(gamfit)
summary(gamma.draws); dim(gamma.draws)

# get log scale prob's for year effects
# these are for the baseline 'line' level, but it's a relative index
# the 'old' delta_glm function calculated "least squares means" (added the mean of the other covariates' levels)
gamma.yrs.log <- cbind.data.frame(year1951=gamma.draws[,1],
                                  gamma.draws[,1] + gamma.draws[,2:length(yr.vec)])

summary(gamma.yrs.log)

# convert to arithmetic scale
gamma.yrs <- exp(gamma.yrs.log)

summary(gamma.yrs)

# plot annual conditional means
plot(yr.vec, apply(gamma.yrs, 2, mean), type='o', xlab='year', ylab='conditional mean CPUE')

########## use the two GLMs to compute the index
# multiply the proportion positives by the conditional means
index.draws <- bin.yrs.prop * gamma.yrs

# get mean index and 95% interval
index <- apply(index.draws, 2, median)
logSE <- apply(index.draws, 2, function(x) { sd(log(x)) }) # this is a common input to our assessment models
int95 <- apply(index.draws, 2, quantile, probs=c(0.025,0.975))
index.df <- cbind.data.frame(index, logSE, t(int95))

index.df 


# formate for SS adding season and survey numbers
years <- as.data.frame(yr.vec) %>% arrange(yr.vec)

ss_data <- cbind(years, index.df) 

ss_data <- ss_data %>% 
  mutate(seas = 1, survey = 6) %>% 
  select(yr.vec, seas, survey, index, logSE) %>% 
  rename(year = yr.vec, obs = index, se_log = logSE) %>% 
  rename(index = survey)

#write.csv(ss_data, "data/CalCOFI_index_year_distblock_gamma.csv", row.names = FALSE)

# plot index and 95% interval
ss_data2 <- cbind(years, index.df) %>% 
  ungroup()

ss_data2 <- ss_data2 %>% 
  mutate(seas = 1, survey = 6, yr.vex = as.numeric(yr.vec))  %>% 
  rename(year = yr.vec, obs = index, se_log = logSE, low = "2.5%", high = "97.5%") %>% 
  mutate(year = as.numeric(as.character(year)) ,low = as.numeric(low), high = as.numeric(high)) %>% 
  rename(index = survey) 

ggplot(ss_data2, aes(year, obs)) +
  geom_line() +
  geom_point() +
  geom_line(data = ss_data2, aes(x = year, y = low, col = "red")) +
  geom_line(data = ss_data2, aes(x = year, y = high, col = "red")) +
  theme_bw() + 
  theme(legend.position = "none") 
```
